/** \file
 *  This C header file was generated by $ANTLR version 3.5.1
 *
 *     -  From the grammar source file : C:\\SPO_labs\\LinuxV\\antlr\\labgramm.g
 *     -                            On : 2025-01-30 09:01:04
 *     -                 for the lexer : labgrammLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
labgrammLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef plabgrammLexer, which is returned from a call to labgrammLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in plabgrammLexer are  as follows:
 *
 *  - 
 void
      plabgrammLexer->T__56(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__57(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__58(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__59(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__60(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__61(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__62(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__63(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__64(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__65(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__66(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__67(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__68(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__69(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__70(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__71(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__72(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__73(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__74(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__75(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__76(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__77(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__78(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__79(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__80(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__81(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__82(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__83(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__84(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__85(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__86(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__87(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->T__88(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->Equal(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->LITERAL(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->BOOL(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->BITS(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->HEX(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->DEC(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->CHAR(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->BUILTINTYPE(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->ID(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->INT(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->ASSIGNMENT_OPERATOR(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->RELATIONAL_OPERATOR(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->ADDITIVE_UNARY_OPERATOR(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->STRING(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->HEX_DIGIT(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->ESC_SEQ(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->OCTAL_ESC(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->WS(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->COMMENT(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->LINE_COMMENT(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->UNICODE_ESC(plabgrammLexer)
 *  - 
 void
      plabgrammLexer->Tokens(plabgrammLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_labgrammLexer_H
#define _labgrammLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct labgrammLexer_Ctx_struct labgrammLexer, * plabgrammLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
labgrammLexer

 */
struct labgrammLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__56)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__57)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__58)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__59)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__60)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__61)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__62)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__63)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__64)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__65)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__66)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__67)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__68)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__69)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__70)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__71)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__72)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__73)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__74)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__75)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__76)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__77)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__78)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__79)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__80)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__81)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__82)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__83)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__84)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__85)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__86)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__87)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mT__88)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mEqual)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mLITERAL)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mBOOL)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mBITS)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mHEX)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mDEC)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mCHAR)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mBUILTINTYPE)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mID)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mINT)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mASSIGNMENT_OPERATOR)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mRELATIONAL_OPERATOR)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mADDITIVE_UNARY_OPERATOR)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mSTRING)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mHEX_DIGIT)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mESC_SEQ)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mOCTAL_ESC)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mLINE_COMMENT)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mUNICODE_ESC)	(struct labgrammLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct labgrammLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct labgrammLexer_Ctx_struct * ctx);
    void	    (*free)   (struct labgrammLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API plabgrammLexer labgrammLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API plabgrammLexer labgrammLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__56      56
#define T__57      57
#define T__58      58
#define T__59      59
#define T__60      60
#define T__61      61
#define T__62      62
#define T__63      63
#define T__64      64
#define T__65      65
#define T__66      66
#define T__67      67
#define T__68      68
#define T__69      69
#define T__70      70
#define T__71      71
#define T__72      72
#define T__73      73
#define T__74      74
#define T__75      75
#define T__76      76
#define T__77      77
#define T__78      78
#define T__79      79
#define T__80      80
#define T__81      81
#define T__82      82
#define T__83      83
#define T__84      84
#define T__85      85
#define T__86      86
#define T__87      87
#define T__88      88
#define ADDITIVE_UNARY_OPERATOR      4
#define ASSIGNMENT_OPERATOR      5
#define ArgDef      6
#define Array      7
#define ArrayList      8
#define Array_Size      9
#define AssignmentOP      10
#define BITS      11
#define BOOL      12
#define BUILTINTYPE      13
#define Body      14
#define Braces      15
#define BreakStatement      16
#define Builtin_Type      17
#define CHAR      18
#define COMMENT      19
#define Call      20
#define Condition      21
#define ConditionStatement      22
#define Custom_Type      23
#define DEC      24
#define Dimensions      25
#define ESC_SEQ      26
#define ElseStatement      27
#define Equal      28
#define Expression      29
#define FuncDef      30
#define FuncSignature      31
#define HEX      32
#define HEX_DIGIT      33
#define ID      34
#define INT      35
#define Ident      36
#define Identifier      37
#define Indexer      38
#define Init_List      39
#define Init_suffix      40
#define Int      41
#define LINE_COMMENT      42
#define LITERAL      43
#define ListID      44
#define LoopStatement      45
#define OCTAL_ESC      46
#define RELATIONAL_OPERATOR      47
#define RepeatStatement      48
#define ReturnStatement      49
#define STRING      50
#define Source      51
#define TypeRef      52
#define UNICODE_ESC      53
#define VarDeclaration      54
#define WS      55
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for labgrammLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
